/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.33.1.
 * @module
 */

import { anyApi } from "convex/server";

export declare const api: any;
export declare const internal: any;
