/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.33.1.
 * @module
 */

import type { GenericId } from "convex/values";

/**
 * A type representing a Convex document ID.
 */
export type Id<TableName extends string = string> = GenericId<TableName>;
export type Doc<TableName extends string = string> = Record<string, any>;
